# Time limits (seconds)
EXECUTION_TIMEOUT_SECONDS = 10

# Docker resource limits
DOCKER_MEMORY_LIMIT = "512m"
DOCKER_MEMORY_SWAP = "512m"
DOCKER_CPU_LIMIT = "1"
DOCKER_PIDS_LIMIT = "64"
DOCKER_NOFILE_LIMIT = "64"

# Output limits
MAX_STDOUT_BYTES = 1_000_000  # 1 MB

# Container behavior
CONTAINER_SLEEP_SECONDS = 20

# Concurrency
MAX_CONCURRENT_EXECUTIONS = 5
