# Time limits (seconds)
EXECUTION_TIMEOUT_SECONDS = 20

# Docker resource limits
DOCKER_MEMORY_LIMIT = "1536m"
DOCKER_MEMORY_SWAP = "1536m"
DOCKER_CPU_LIMIT = "4"
DOCKER_PIDS_LIMIT = "256"
DOCKER_NOFILE_LIMIT = "256"

# Output limits
MAX_STDOUT_BYTES = 1_000_000  # 1 MB

# Container behavior
CONTAINER_SLEEP_SECONDS = 30

# Concurrency
MAX_CONCURRENT_EXECUTIONS = 15
